export const ERROR_TYPES = {
    // Requesting
    REQUEST_FAILED: 'REQUEST_FAILED',

    // Validation
    FIELD_REQUIRED: 'FIELD_REQUIRED',
    INVALID_LENGTH: 'INVALID_LENGTH',
    INVALID_FORMAT: 'INVALID_FORMAT',
    INVALID_WALLET_ADDRESS: 'INVALID_WALLET_ADDRESS',

    // User password
    INVALID_PASSWORD: 'INVALID_PASSWORD',
};


export default ERROR_TYPES;
