export const ERROR_TYPES = {
    // Requesting
    REQUEST_FAILED: 'REQUEST_FAILED',

    // Validation
    FIELD_REQUIRED: 'FIELD_REQUIRED',
    INVALID_LENGTH: 'INVALID_LENGTH',
    INVALID_FORMAT: 'INVALID_FORMAT',
};


export default ERROR_TYPES;
